site_name: '@johannes.latzel/llm-chat-web'
site_url: https://johanneslatzel.github.io/llm-chat-web/
repo_url: https://github.com/johanneslatzel/llm-chat-web
theme:
    name: material
    palette:
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
nav:
    - Overview: index.md
    - Architecture: architecture.md
    - Environment Variables: configuration.md
    - Quick Start: quickstart.md
plugins:
    - search
